name: Tauri

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install bun
      run: |
        curl -fsSL https://bun.sh/install | bash
        echo 'export BUN_INSTALL="$HOME/.bun"' >> ~/.profile
        echo 'export PATH="$BUN_INSTALL/bin:$PATH"' >> ~/.profile
        source ~/.profile

    - name: Verify bun installation
      run: |
        source ~/.profile
        echo $PATH
        bun --version

    - name: Build
      run: |
        source ~/.profile
        bun i
        bun tauri build --verbose

