name: Tauri

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install bun
      run: |
        curl -fsSL https://bun.sh/install | bash
        echo 'export BUN_INSTALL="$HOME/.bun"' >> ~/.bashrc
        echo 'export PATH="$BUN_INSTALL/bin:$PATH"' >> ~/.bashrc
        source ~/.bashrc

    - name: Verify bun installation
      shell: bash -l {0}
      run: |
        echo $PATH
        bun --version

    - name: Build
      shell: bash -l {0}
      run: |
        bun tauri build --verbose
