name: Tauri

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install bun
      run: |
        powershell -c "irm bun.sh/install.ps1 | iex"

    - name: Verify bun installation
      run: |
        bun --version

    - name: Build
      run: |
        bun i
        bun tauri build --verbose

